// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ExternalLogin struct {
	Sub       string      `json:"sub"`
	Uid       pgtype.UUID `json:"uid"`
	GrantType pgtype.Text `json:"grant_type"`
	Provider  pgtype.Text `json:"provider"`
}

type UserAccount struct {
	Uid       pgtype.UUID      `json:"uid"`
	FullName  string           `json:"full_name"`
	Username  pgtype.Text      `json:"username"`
	Email     string           `json:"email"`
	Gender    pgtype.Text      `json:"gender"`
	AvatarUri pgtype.Text      `json:"avatar_uri"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type UserLoginInternal struct {
	ID             int64       `json:"id"`
	Uid            pgtype.UUID `json:"uid"`
	GrantType      pgtype.Text `json:"grant_type"`
	Email          string      `json:"email"`
	EmailVerified  pgtype.Bool `json:"email_verified"`
	PhoneNumber    string      `json:"phone_number"`
	HashedPassword string      `json:"hashed_password"`
	Salt           string      `json:"salt"`
}
