// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: query_user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserById = `-- name: GetUserById :one
SELECT uid, full_name, username, email, gender, avatar_uri, created_at, updated_at
FROM user_account
WHERE uid = $1
LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, uid pgtype.UUID) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserById, uid)
	var i UserAccount
	err := row.Scan(
		&i.Uid,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.Gender,
		&i.AvatarUri,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
