// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetUserById(ctx context.Context, uid pgtype.UUID) (UserAccount, error)
}

var _ Querier = (*Queries)(nil)
